apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l73g4s6ys-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l73g4s6ys-go 
  name: l73g4s6ys-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l73g4s6ys-go 
